name: README Update Automation

on:
  pull_request:
    types: [closed]

jobs:
  update-readme:
    name: Update README after PR merge
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      # Check out the repo to access its content
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Python using the latest stable version
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      # Install Python dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the Python script
      - name: Generate Updated README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: python main.py

      # Additional step to enable debugging
      - name: Enable Debug Logging
        run: |
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
